import {
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import store from '../../store'

const navigationConfig: NavigationTree[] = [
  {
    key: 'home',
    path: '/home',
    title: 'Dashboard',
    translateKey: 'nav.dashboard',
    icon: 'sales',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'academy',
    path: '/academy',
    title: 'Academia',
    translateKey: 'nav.dashboard',
    icon: 'academy',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  {
    key: 'pay-supreme',
    path: '/subscriptions',
    title: 'Membresías',
    translateKey: 'nav.pay-supreme',
    icon: 'memberships',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER', 'STARTER'],
    subMenu: [],
  },
  {
    key: 'order-list',
    path: `/order-list`,
    title: 'UNINIVEL',
    translateKey: 'nav.order-list',
    icon: 'direct-people',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  {
    key: 'binary',
    path: `/binary`,
    title: 'Binario',
    translateKey: 'nav.order-list',
    icon: 'binary',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  /*{
    key: 'sanguine-map',
    path: `/report-sanguine-map`,
    title: 'Mapa',
    translateKey: 'nav.order-list',
    icon: 'map',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },*/
  {
    key: 'rank',
    path: `/rank`,
    title: 'Rango',
    translateKey: 'nav.order-list',
    icon: 'rank',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  {
    key: 'user-payroll.history',
    path: `/payroll/history`,
    title: 'Historial de pagos',
    translateKey: 'nav.order-list.history',
    icon: 'payroll',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },
  /*{
    key: '8',
    path: `/shop`,
    title: 'Top Shop',
    translateKey: 'nav.order-list',
    icon: 'leader',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
  },*/
  {
    key: '2',
    path: `/le`,
    title: 'Marketplace',
    translateKey: 'nav.order-list',
    icon: 'marketplace',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER'],
    subMenu: [],
    href: `https://www.empoweritup.com/?user=${
      store?.getState()?.auth?.user?.uid ?? ''
    }&accessToken=`,
  },
  /*{
    key: '5',
    path: `/academy-leadership`,
    title: 'Sistema de liderazgo',
    translateKey: 'nav.order-list',
    icon: 'system',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['USER', 'STARTER'],
    subMenu: [],
  },*/
  {
    key: 'admin-payroll',
    path: `/admin-payroll`,
    title: 'ADMIN: Pagos',
    translateKey: 'nav.order-list',
    icon: 'payroll',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN'],
    subMenu: [
      {
        key: 'admin-payroll.withdraw',
        path: `/admin-payroll/withdraw`,
        title: 'Retirar',
        translateKey: 'nav.order-list.withdraw',
        icon: 'withdraw',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-payroll.pays',
        path: `/admin-payroll/pays`,
        title: 'Pagar',
        translateKey: 'nav.order-list.pays',
        icon: 'payroll',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-payroll.history',
        path: `/admin-payroll/history`,
        title: 'Historial de pagos',
        translateKey: 'nav.order-list.history',
        icon: 'payroll',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
    ],
  },
  {
    key: 'admin',
    path: `/admin-`,
    title: 'ADMIN: Academia',
    translateKey: 'nav.order-list',
    icon: 'academy',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'EDUCATOR'],
    subMenu: [
      {
        key: 'admin.academy',
        path: `/academy/agregar`,
        title: 'Agregar Curso',
        translateKey: 'nav.videos',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
      {
        key: 'admin.editAcademy',
        path: `/academy/admin-course`,
        title: 'Administrar Cursos',
        translateKey: 'nav.adminCourse',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
    ],
  },
  {
    key: 'admin-liderazgo',
    path: `/admin-liderazgo`,
    title: 'ADMIN: Sistema de Liderazgo',
    translateKey: 'nav.order-list',
    icon: 'system',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'EDUCATOR'],
    subMenu: [
      {
        key: 'admin.leadership',
        path: `/academy-leadership/agregar`,
        title: 'Agregar Curso',
        translateKey: 'nav.videos',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
      {
        key: 'admin.editLeadership',
        path: `/academy-leadership/admin-course`,
        title: 'Administrar Cursos',
        translateKey: 'nav.adminCourse',
        icon: 'videos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'EDUCATOR'],
        subMenu: [],
      },
    ],
  },
  {
    key: 'users-admin',
    path: `/users-admin`,
    title: 'ADMIN: Usuarios',
    translateKey: 'nav.order-list',
    icon: 'users',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['ADMIN', 'SUPPORT'],
    subMenu: [
      {
        key: 'report-earnings',
        path: `/report-earnings`,
        title: 'TOP Ganancias Mensuales',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'report-referrals',
        path: `/report-referrals`,
        title: 'TOP Inscripciones Directas',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'report-map',
        path: `/report-map`,
        title: 'Mapa De Usuarios',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'admin-register',
        path: `/admin-register`,
        title: 'Form. Registro',
        translateKey: 'nav.order-list',
        icon: 'pencil',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'payments-history',
        path: `/payments-history`,
        title: 'Historial de registro/pagos',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'search-users',
        path: `/search-users`,
        title: 'Buscar usuarios',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN'],
        subMenu: [],
      },
      {
        key: 'enter-as-user',
        path: `/admin/enter-as-user`,
        title: 'Entrar como otro usuario',
        translateKey: 'nav.order-list',
        icon: 'history',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['ADMIN', 'SUPPORT'],
        subMenu: [],
      },
    ],
  },
]

export default navigationConfig
